name: mobile
description: VTAAT App Mobile.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  get: ^4.6.5
  firebase_crashlytics: ^3.3.4
  flex_color_scheme: ^6.1.2
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  intl: ^0.18.1
  timeago: ^3.5.0
  loader_overlay: ^2.3.0
  firebase_messaging: ^14.6.5
  permission_handler: ^10.4.3
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.2.3
  device_info_plus: ^9.0.3
  url_launcher: ^6.1.11
  html: ^0.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/